config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :schools
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'community' => 'pages#community'
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">© 2018 Check a School, ID 51772933.</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    
    <i class="fas fa-pencil-alt"></i><%= link_to "Check a School", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_with(url: schools_path, class: "form-inline my-2 my-lg-0 mr-auto", local: true, method: :get) do |f| %>
      <%= f.text_field :near, class: "form-control  mr-sm-2", placeholder: "Enter place or postcode" %>
      <%= f.submit "Search", class: "btn btn-outline-secondary my-2 my-sm-0" %>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Check a School", schools_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Community", community_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary my-2 my-sm-0" %></li>
        <% end %>
      </ul>
    </div>
    
  </div>
</nav>