config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :schools
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'community' => 'pages#community'
end

app/models/school.rb
class School < ApplicationRecord
has_one :ks2result
has_one :ks4result

extend FriendlyId
friendly_id :urn, use: :slugged
alias_attribute :slug, :urn

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  
  def address
    [street, locality, address3, town, postcode].compact.join(', ')
  end

  def address_changed?
    street_changed? || town_changed? || locality_changed? || address3_changed? || postcode_changed?
  end
  
  def self.search(keyword)
  
    if keyword
      where("LOWER(name) LIKE ?", "%#{keyword.downcase}%").order('NAME').limit(50)
    end
  
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:edit, :update, :destroy]
  before_action :authenticate_admin, except: [:index, :show]

  # GET /schools
  # GET /schools.json
  def index
    @schools = if params[:l]
                      sw_lat, sw_lng, ne_lat, ne_lng = params[:l].split(",")
                      center   = Geocoder::Calculations.geographic_center([[sw_lat, sw_lng], [ne_lat, ne_lng]])
                      distance = Geocoder::Calculations.distance_between(center, [sw_lat, sw_lng])
                      box      = Geocoder::Calculations.bounding_box(center, distance)
                      School.within_bounding_box(box)
                    elsif params[:near]
                      if School.near(params[:near], 1.5).any?
                        School.near(params[:near], 1.5)
                      else
                        School.near('London', 2)
                      end
                    else
                      @location_info = request.location
                      if @location_info && School.near([@location_info.latitude, @location_info.longitude], 2).any?
                        School.near([@location_info.latitude, @location_info.longitude], 2)
                      else
                        School.near('London', 2)
                      end
                    end
                    
    @schoolz = School.search(params[:keyword])
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @schools = []
    @schools << School.friendly.find(params[:id])
    
    @exp_standard_local = "67%"
    @exp_standard_england = "61%"
    @higher_standard_local = "13%"
    @higher_standard_england = "9%"
    
    @maths_score_local = 105
    @maths_score_england = 104
    @reading_score_local = 106
    @reading_score_england = 104
    
    @attain8_score_local = 50
    @attain8_score_england = 44.6
    
    @prog8_score_local = 0
    @prog8_score_england = 0
    
    @grade5_or_above_local = "51.6%"
    @grade5_or_above_england = "39.6%"
    
    unless @schools[0].ks2result.nil? 
    @data1 = [
               ["This school", @schools[0].ks2result.exp_standard], 
               ["Local authority average", @exp_standard_local],
               ["England average", @exp_standard_england]
              ] 
    end
    
    unless @schools[0].ks2result.nil? 
    @data2 = [
               ["This school", @schools[0].ks2result.higher_standard], 
               ["Local authority average", @higher_standard_local],
               ["England average", @higher_standard_england]
              ] 
    end
    
    unless @schools[0].ks2result.nil? 
    @data3 = [
               ["This school", @schools[0].ks2result.mat_average], 
               ["Local authority average", @maths_score_local],
               ["England average", @maths_score_england]
              ] 
    end
    
    unless @schools[0].ks2result.nil? 
    @data4 = [
               ["This school", @schools[0].ks2result.read_average], 
               ["Local authority average", @reading_score_local],
               ["England average", @reading_score_england]
              ] 
    end

    unless @schools[0].ks2result.nil? 
    @data5 = [
               ["This school", @schools[0].ks2result.read_progress] 
               
              ] 
    end
    
    unless @schools[0].ks2result.nil? 
    @data6 = [
               ["This school", @schools[0].ks2result.write_progress] 
               
              ] 
    end
    
    unless @schools[0].ks2result.nil? 
    @data7 = [
               ["This school", @schools[0].ks2result.mat_progress] 
               
              ] 
    end
    
    
    @attain8_score_local = 50
    @attain8_score_england = 44.6
    
    @prog8_score_local = 0
    @prog8_score_england = 0
    
    @grade5_or_above_local = "51.6%"
    @grade5_or_above_england = "39.6%"
    
    unless @schools[0].ks4result.nil? 
    @ks4_data1 = [
               ["This school", @schools[0].ks4result.attain8_score], 
               ["Local authority average", @attain8_score_local],
               ["England average", @attain8_score_england]
              ] 
    end
    
    unless @schools[0].ks4result.nil? 
    @ks4_data2 = [
               ["This school", @schools[0].ks4result.prog8_score], 
               ["Local authority average", @prog8_score_local],
               ["England average", @prog8_score_england]
              ] 
    end

    unless @schools[0].ks4result.nil? 
    @ks4_data3 = [
               ["This school", @schools[0].ks4result.grade5_or_above], 
               ["Local authority average", @grade5_or_above_local],
               ["England average", @grade5_or_above_england]
              ] 
    end
    
    respond_to do |format|
    format.html
    format.json { render json: @schools[0].to_json(include: [:ks2result, :ks4result] )}
    end
    
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:urn, :integer, :la, :integer, :name, :other_name, :street, :locality, :address3, :town, :postcode, :telnum, :minorgroup, :nftype, :isprimary, :issecondary, :is, :post16, :agel, :ageh, :gender, :reldenom, :admpol, :read_average, :mat_average, :keyword)
    end
    
    def authenticate_admin
      unless current_user.try(:admin?)
        redirect_to '/', alert: 'You are not authorised to access that page'
      end
    end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<div class="container-fluid">
    
  <div class="row">
    <div class="col-md-4 offset-md-4">
  
  <%= form_with(model: school, local: true) do |form| %>
  
  <form>
    <% if school.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>
  
        <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group-row">
      <%= form.label :urn, class: "col-form-label" %>
      <%= form.text_field :urn, id: :school_urn, class: "form-control" %>
    </div>
    
    <div class="form-group-row">
      <%= form.label :la %>
      <%= form.text_field :la, id: :school_la, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :name %>
      <%= form.text_field :name, id: :school_name, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :other_name %>
      <%= form.text_field :other_name, id: :school_other_name, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :street %>
      <%= form.text_field :street, id: :school_street, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :locality %>
      <%= form.text_field :locality, id: :school_locality, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :address3 %>
      <%= form.text_field :address3, id: :school_address3, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :town %>
      <%= form.text_field :town, id: :school_town, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :postcode %>
      <%= form.text_field :postcode, id: :school_postcode, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :telnum %>
      <%= form.number_field :telnum, id: :school_telnum, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :minorgroup %>
      <%= form.text_field :minorgroup, id: :school_minorgroup, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :nftype %>
      <%= form.text_field :nftype, id: :school_nftype, class: "form-control" %>
    </div>
  
    <div class="form-check">
      <%= form.label :isprimary, class: "form-check-label" %>
      <%= form.check_box :isprimary, id: :school_isprimary, class: "form-check-input" %>
    </div>
  
    <div class="form-check">
      <%= form.label :issecondary, class: "form-check-label" %>
      <%= form.check_box :issecondary, id: :school_issecondary, class: "form-check-input" %>
    </div>
  
    <div class="form-check">
      <%= form.label :ispost16, class: "form-check-label" %>
      <%= form.check_box :ispost16, id: :school_ispost16, class:"form-check-input" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :agel %>
      <%= form.number_field :agel, id: :school_agel, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :ageh %>
      <%= form.number_field :ageh, id: :school_ageh, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :gender %>
      <%= form.text_field :gender, id: :school_gender, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :reldenom %>
      <%= form.text_field :reldenom, id: :school_reldenom, class: "form-control" %>
    </div>
  
    <div class="form-group-row">
      <%= form.label :admpol %>
      <%= form.text_field :admpol, id: :school_admpol, class: "form-control" %>
    </div><br>
  
    <div>
      <%= form.submit "Save changes", class: "btn btn-primary" %>
    </div>
  <% end %>
  
  </form>
  </div>
  </div>

</div>

app/views/schools/edit.html.erb
<div class="col"><br>
  <h1 class="text-center">Edit School</h1>
  <%= render 'form', school: @school %>
  <p class="text-center">
    <%= link_to 'Show', @school %> |
    <%= link_to 'Back', schools_path %>
  </p>
</div>

app/views/schools/index.html.erb
<div class="container-fluid">
  <div class="row">
    
    <div class="col-12">
      <%= tag.div nil, id: 'map', data: { schools: @schools.to_json(methods: [:address]), l: params[:l] } %>
    </div>
    
    </div>
    
    <div class="row h-100">
      
    <div class="col-md-4 offset-md-2 my-auto"><br>
      <%= button_to "Redo search in this area to view more schools", "#", id: "redo-search", 
      class: "btn btn-outline-primary btn-block btn-lg" %>
    </div>
    
    
    <div class= "col-md-5 my-auto"><br>
      <%= form_tag schools_path, method: :get, class: "form-inline" do %>
        <%= text_field_tag :keyword, params[:keyword], placeholder: 'Enter school name or its part', 
        class: "form-control form-control-lg mr-sm-2 col-md-8  text-center" %>
        <%= submit_tag 'Search', class: "btn btn-outline-success btn-lg my-2 my-sm-0" %>
      <% end %>
    </div>
    
    <div class="col-md-12"><br>
      <% if params[:keyword] && !@schoolz.empty? %>
      
        <% if @schoolz.count == 50 %>
          <p class="text-center">We have found more than 50 schools, only first 50 schools are shown below. 
          Please try anohter search or use search by location form on top.</p>
          <% @schoolz.each do |school| %>
          |<%= link_to school.name, school_path(school), target: :_blank %> |
          <% end %>
          
         <% elsif params[:keyword] && !@schoolz.empty? && @schoolz.count == 1 %>
          <p class="text-center">We have found a school as follows:
          <% @schoolz.each do |school| %>
          <%= link_to school.name, school_path(school), target: :_blank %> </p>
          <% end %>
        
        <% else %> 
          <p class="text-center">We have found <%= @schoolz.count %> schools as follows:</p>
          <% @schoolz.each do |school| %>
          | <%= link_to school.name, school_path(school), target: :_blank %> |
          <% end %>
        <% end %>
       
      <% elsif params[:keyword]  %>
         <p class="text-center">Nothing is found. Please try another search or search by location using the form on top. 
         Alternatively, search on the map by zooming in and out and dragging the map.</p>
      <% end %>
      
    </div>

  </div>
</div>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>